//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.18
//
package com.amazonaws.mobile;

import android.graphics.Color;

import com.amazonaws.mobilehelper.config.AWSMobileHelperConfiguration;
import com.amazonaws.regions.Regions;
import com.kevinsperrine.woodstock.R;

/**
 * This class defines constants for the developer's resource
 * identifiers and API keys. This configuration should not
 * be shared or posted to any public source code repository.
 */
public class AWSConfiguration {
    // AWS MobileHub user agent string
    public static String AWS_MOBILEHUB_USER_AGENT =
        "MobileHub 2eab60f0-e346-4f37-9946-6d5b8515313d aws-my-sample-app-android-v0.18";
    // AMAZON COGNITO
    public static Regions AMAZON_COGNITO_REGION =
      Regions.fromName("us-east-1");
    public static String  AMAZON_COGNITO_IDENTITY_POOL_ID =
        "us-east-1:18f7a706-f16c-45fa-a1c4-790b2c93ddd1";
    // AMAZON MOBILE ANALYTICS
    public static String  AMAZON_MOBILE_ANALYTICS_APP_ID =
        "4dca8c0e8d98417e8606a657c610ba98";
    // Amazon Mobile Analytics region
    public static Regions AMAZON_MOBILE_ANALYTICS_REGION = Regions.US_EAST_1;
    // GOOGLE CLOUD MESSAGING SENDER ID
    public static String GOOGLE_CLOUD_MESSAGING_SENDER_ID =
        "908475700363";

    private static AWSMobileHelperConfiguration helperConfiguration = new AWSMobileHelperConfiguration.Builder()
        .withCognitoRegion(AMAZON_COGNITO_REGION)
        .withCognitoIdentityPoolId(AMAZON_COGNITO_IDENTITY_POOL_ID)
        .build();
    /**
     * @return the configuration for AWSKit.
     */
    public static AWSMobileHelperConfiguration getAWSMobileHelperConfiguration() {
        return helperConfiguration;
    }
}
